# Generated by Django 2.0.3 on 2018-04-16 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'verbose_name': '简历基础信息', 'verbose_name_plural': '简历基础信息'},
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
